package com.exception.handelling.custome;

public class Test {

	public static void main(String[] args) throws CustomeException {

		throw new CustomeException("Some exception occured");

	}

}
